# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ru Li
title: Ph.D. in UESTC
email: liru@std.uestc.edu.cn
# website: liru0126.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  liru0126
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google scholar
  icon: fab fa-google
  url: https://scholar.google.com.sg/citations?hl=zh-CN&user=4cHM8rYAAAAJ
# - title: another link
#   icon: fas fa-envelope
#   url: https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&to=liru@std.uestc.edu.cn

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me  
about_title: Biography
about_profile_image: images/yearyear.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a fourth-year Ph.D. student of machine learning and computer vision under the supervision of 
  [Prof. Guanghui LIU](https://scholar.google.com.hk/citations?user=AjfD95EAAAAJ&hl=zh-CN&oi=ao) and 
  [Prof. Shuaicheng LIU](http://www.liushuaicheng.org/) at University of Electronic Science and Technology of China (UESTC). 
  Meanwhile, I start my internship at Megvii Research since 2018. My research interests include Generative Adversarial Networks (GAN), image processing, etc.

content:

  - title: Education & Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ph.D. 
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: Signal and Information Processing
        caption: Sep. 2018 - Present
        description: | # this will include new lines to allow paragraphs
            ## **Uinversity of Electronic Science and Technology of China (UESTC)**

            Signal and Information Processing
        
      - layout: left
        title: M.Sc.
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: Signal and Information Processing
        caption: Sep. 2016 - Jul. 2018
        description: | # this will include new lines to allow paragraphs
            ## **Uinversity of Electronic Science and Technology of China (UESTC)**

            Signal and Information Processing
            
      - layout: left
        title: B.E.
        # link: bmwgroup.com
        # link_text: bmwgroup.com
        # sub_title: Electronic Information Engineering
        caption: Sep. 2012 - Jul. 2016
        description: | # this will include new lines to allow paragraphs     
            ## **China University of Petroleum (UPC)**

            Electronic Information Engineering
            
      - layout: left
        title: Visiting student
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption: Jul. 2019 - Otc. 2019
        description: | # this will include new lines to allow paragraphs
            ## **University of Oxford**
            
      - layout: left
        title: Intern
        # link: www.msg.group
        # link_text: msg.group
        # sub_title: 
        caption: Mar. 2018 - Present
        description: | # this will include new lines to allow paragraphs
            ## **Megvii Research**
            
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        title: 2021
        description: | # this will include new lines to allow paragraphs
          ## **Image Style Transfer with Generative Adversarial Networks**

          *ACM Multimedia (**ACMMM**), pp. 2950-2954, 2021*

          **Ru Li**

          [[PDF](https://dl.acm.org/doi/abs/10.1145/3474085.3481029)]
          [Github]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:wTKe9EwnqrgJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29RuVNzQ:AAGBfm0AAAAAYZ-TLzRp9SlMufWIlSjwk5INj_C2c3f-&scisig=AAGBfm0AAAAAYZ-TLyiFuWClDAc3ljw0JzPOWeKheCzA&scisf=4&ct=citation&cd=-1&hl=zh-CN)]
    
      - layout: left
        # title: 2021
        description: | # this will include new lines to allow paragraphs
          ## **UPHDR-GAN: Generative Adversarial Network for High Dynamic Range Imaging with Unpaired Data**

          *Preprint*

          **Ru Li**, Chuan Wang, Shuaicheng Liu, Jue Wang, Guanghui Liu, Bing Zeng

          [[PDF](https://arxiv.org/pdf/2102.01850.pdf)]
          [Github]
          [BibTex]
          
      - layout: left
        # title: 2021
        description: | # this will include new lines to allow paragraphs
          ## **JigsawGAN: Auxiliary Learning for Solving Jigsaw Puzzles with Generative Adversarial Networks**

          *IEEE Transactions on Image Processing (**TIP**), to appear, 2021*

          **Ru Li**, Shuaicheng Liu, Guangfu Wang, Guanghui Liu, Bing Zeng

          [PDF]
          [Github]
          [BibTex]

      - layout: left
        # title: 2021
        description: | # this will include new lines to allow paragraphs
          ## **Quadratic Terms based Point-to-Surface 3D Representation for Deep Learning of Point Cloud**

          *IEEE Transactions on Circuits and Systems for Video Technology (**TCSVT**), to appear, 2021*

          Tiecheng Sun, Guanghui Liu, **Ru Li**, Shuaicheng Liu, Shuyuan Zhu, Bing Zeng
          
          [PDF]
          [Github]
          [BibTex]
          
      - layout: left
        title: 2020 
        description: | # this will include new lines to allow paragraphs
          ## **SDP-GAN: Saliency Detail Preservation Generative Adversarial Networks for High Perceptual Quality Style Transfer**

          *IEEE Transactions on Image Processing (**TIP**), vol. 30, pp. 374-385, 2020*

          **Ru Li**, Chi-Hao Wu,  Shuaicheng Liu, Jue Wang, Guangfu Wang, Guanghui Liu, Bing Zeng
          
          [[PDF](http://liushuaicheng.org/TIP/SDPGAN/SDPGAN-TIP.pdf)]
          [[Github](https://github.com/liru0126/SDP-GAN)]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:-M_dxm-pX5kJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29Rtt94Y:AAGBfm0AAAAAYZ9r74bW1gyUro3hB0wK0mcgI3uKkoKs&scisig=AAGBfm0AAAAAYZ9r7_22OCu7DHTXiSpJICPblJX5VWn3&scisf=4&ct=citation&cd=-1&hl=zh-CN)]
          
      - layout: left
        # title: 2020 
        description: | # this will include new lines to allow paragraphs
          ## **Multi-exposure photomontage with hand-held cameras**

          *Computer Vision and Image Understanding (**CVIU**), vol. 193, pp. 102929, 2020*

          **Ru Li**, Shuaicheng Liu, Guanghui Liu, Tiecheng Sun, Jishun Guo
          
          [[PDF](http://www.liushuaicheng.org/CVIU/Exposure-Montage-CVIU.pdf)]
          [Github]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:iX_Pb5JdYPgJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29RtqXjs:AAGBfm0AAAAAYZ9sRjv5SV9JLIUk5KTZj9Wb6sja5aOY&scisig=AAGBfm0AAAAAYZ9sRmzXa_m61iA0cdCIHrtCtQ7pt7BE&scisf=4&ct=citation&cd=-1&hl=zh-CN)]

      - layout: left
        # title: 2020 
        description: | # this will include new lines to allow paragraphs
          ## **An Efficient and Compact 3D Local Descriptor based on the Weighted Height Image**

          *Information Sciences (**INS**), vol. 520, pp. 209-231, 2020*

          Tiecheng Sun, Guanghui Liu, Shuaicheng Liu, Fanman Meng, Liaoyuan Zeng, **Ru Li**
          
          [[PDF](http://www.liushuaicheng.org/INS/3DLD_IS.pdf)]
          [Github]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:EMaVxISMTv4J:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29Rtqn2I:AAGBfm0AAAAAYZ9sh2KQ6J9bjVvlc23FNpVl0K2ws2ts&scisig=AAGBfm0AAAAAYZ9sh0O133r5cB_7xaSZZPla_bbIRuVp&scisf=4&ct=citation&cd=-1&hl=zh-CN)]

      - layout: left
        title: 2019
        description: | # this will include new lines to allow paragraphs
          ## **Hybrid Synthesis for Exposure Fusion from Hand-Held Camera Inputs**

          *IEEE Internation Conference on Image Processing (**ICIP**), pp. 4639-4643, 2019*

          **Ru Li**, Shuaicheng Liu, Guanghui Liu, Bing Zeng
          
          [[PDF](https://ieeexplore.ieee.org/abstract/document/8803689)]
          [Github]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:4Pl5_ZPmbvYJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29RtqtF8:AAGBfm0AAAAAYZ9srF9xpz-ACxyuYr63muGEB2DsntJf&scisig=AAGBfm0AAAAAYZ9srFPTQHDqP2hqBh4xAOmMmfZ1zmax&scisf=4&ct=citation&cd=-1&hl=zh-CN&scfhb=1)]

      - layout: left
        title: 2018
        description: | # this will include new lines to allow paragraphs
          ## **Photomontage for robust hdr imaging with hand-held cameras**

          *IEEE Internation Conference on Image Processing (**ICIP**), pp. 1708-1712, 2018*

          **Ru Li**, Xiaowu He, Shuaicheng Liu, Guanghui Liu, Bing Zeng
          
          [[PDF](http://www.liushuaicheng.org/ICIP/2018/HDR_ICIP18.pdf)]
          [Github]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:-87rfPbBywgJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29RtrGao:AAGBfm0AAAAAYZ9tAaoahz0wVb-RX7wlHOhxQj3ZIxCm&scisig=AAGBfm0AAAAAYZ9tAdT3TRdjghHFTlVZmuBj0N-o8wFb&scisf=4&ct=citation&cd=-1&hl=zh-CN)]

      - layout: left
        title: 2016
        description: | # this will include new lines to allow paragraphs
          ## **Multiple kernel collaborative representation based classification**

          *IEEE Internation Conference on Signal Processing (**ICSP**), pp. 826-831, 2016*

          **Ru Li**, Qian Zhang, Zhiming Gao, Bao-Di Liu, Yanjing Wang
          
          [[PDF](https://ieeexplore.ieee.org/abstract/document/7877946)]
          [Github]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:UZWd2xLqBUkJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29RtrIDI:AAGBfm0AAAAAYZ9tODJggwRrZ6uooNT4myQmu9khIJsS&scisig=AAGBfm0AAAAAYZ9tOCnNaUUzo9wEEiTbUK9yKfO80tZ0&scisf=4&ct=citation&cd=-1&hl=zh-CN)]

      - layout: left
        # title: 2016 
        description: | # this will include new lines to allow paragraphs
          ## **Kernel class specific centralized dictionary learning for face recognition**

          *IEEE Internation Conference on Signal Processing (**ICSP**), pp. 837-842, 2016*

          Zhiming Gao, Qian Zhang, **Ru Li**, Bao-Di Liu, Yanjing Wang
          
          [[PDF](https://ieeexplore.ieee.org/abstract/document/7877948)]
          [Github]
          [[BibTex](https://scholar.googleusercontent.com/scholar.bib?q=info:Kv32L_F4IRQJ:scholar.google.com/&output=citation&scisdr=CgX3wfUqEIy29RtrkZ8:AAGBfm0AAAAAYZ9tiZ88crDG2V-PJ_LiiJbkoFn7oIC3&scisig=AAGBfm0AAAAAYZ9tiVXnSKNgB3arEleNk6X92XByM-Qq&scisf=4&ct=citation&cd=-1&hl=zh-CN)]

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Driver Monitor System
        caption: Dec. 2018 - Jul. 2019
        sub_title: Major member
        description: | # this will include new lines to allow paragraphs
          I am responsible for designing a light-weighted end-to-end network running on an onboard chip to detect smoking, phoning, 
          and drinking in driving. Participated in the overall pipeline of algorithm development, including data collection, 
          data cleaning, algorithm development, and upgrading.
        video_path: images/DMS_smoke_demo1.mp4
        video_path1: images/DMS_smoke_demo2.mp4
        video_path2: images/DMS_phone_demo.mp4
           
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
