# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ru Li
title: Ph.D. in UESTC
email: liru@std.uestc.edu.cn
# website: liru0126.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  liru0126
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google scholar
  icon: fab fa-google
  url: https://scholar.google.com.sg/citations?hl=zh-CN&user=4cHM8rYAAAAJ
# - title: another link
#   icon: fas fa-envelope
#   url: https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&to=liru@std.uestc.edu.cn

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me  
about_title: Biography
about_profile_image: images/landscape-trees.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a fourth-year Ph.D. student of machine learning and computer vision under the supervision of 
  [Prof. Guanghui LIU](https://scholar.google.com.hk/citations?user=AjfD95EAAAAJ&hl=zh-CN&oi=ao) and 
  [Prof. Shuaicheng LIU](http://www.liushuaicheng.org/) at University of Electronic Science and Technology of China (UESTC). 
  Meanwhile, I start my internship at Megvii Research since 2018. My research interests include Generative Adversarial Networks (GAN), image processing, etc.

content:

  - title: Education & Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ph.D. 
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: Signal and Information Processing
        caption: Sep. 2018 - Present
        description: | # this will include new lines to allow paragraphs
            ## **Uinversity of Electronic Science and Technology of China (UESTC)**

            Signal and Information Processing
        
      - layout: left
        title: M.Sc.
        # link: grubhub.com
        # link_text: grubhub.com
        # sub_title: Signal and Information Processing
        caption: Sep. 2016 - Jul. 2018
        description: | # this will include new lines to allow paragraphs
            ## **Uinversity of Electronic Science and Technology of China (UESTC)**

            Signal and Information Processing
            
      - layout: left
        title: B.E.
        # link: bmwgroup.com
        # link_text: bmwgroup.com
        # sub_title: Electronic Information Engineering
        caption: Sep. 2012 - Jul. 2016
        description: | # this will include new lines to allow paragraphs     
            ## **China University of Petroleum (UPC)**

            Electronic Information Engineering
            

           
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
